In [3]:
from exchange_calendars import register_calendar, get_calendar
from dse_bundles.lib.exchange_calendar_xdse import XDSExchangeCalendar
import july
import pandas as pd
import matplotlib.pyplot as plt

In [61]:
from glob import glob

In [4]:
register_calendar("XDSE", XDSExchangeCalendar())
xdse = get_calendar("XDSE")

In [65]:
session = xdse.schedule.loc['2012-01-01':'2021-12-31']
session = [x.date() for x in session.market_close]
files = glob("./before_process_data/csv/*")
for each in files:
    symbol = each.split("/")[-1]
    print(symbol)
    data = pd.read_csv(each, index_col='date', parse_dates=True)
    index = [x.date() for x in data.index]
    to_remove = list(set(index) - set(session))
    print(to_remove)
    data = data[~data.index.isin(to_remove)]
    data.to_csv(f"./dse_bundles/data/daily/{symbol}")

MHSML.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BATASHOE.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
UNIQUEHRL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BBSCABLES.csv
[]
ACTIVEFINE.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
TITASGAS.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BERGERPBL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
UPGDCL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
WMSHIPYARD.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
DBH.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ITC.csv
[datetime.date(2016, 9, 24), datetime.date(2016, 7, 16)]
UTTARABANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BBS.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BXPHARMA.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
MERCANBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SHASHADNIM.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PREMIERCEM.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SSSTEEL.csv
[]
BARKAPOWER.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BDFINANCE.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
KPCL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
IFADAUTOS.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BRACBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PRIMEBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ESQUIRENIT.csv
[]
LHBL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SQUARETEXT.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
KEYACOSMET.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
RSRMSTEEL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
RAKCERAMIC.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SUMITPOWER.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
RUPALIBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
RENATA.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
IFIC.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PRAGATIINS.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BSCCL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SAMATALETH.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
RECKITTBEN.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PTL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
GHAIL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
VFSTDL.csv
[]
ACFL.csv
[]
WATACHEM.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
CVOPRL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
AFCAGRO.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
RUNNERAUTO.csv
[]
FEKDIL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SHEPHERD.csv
[]
NCCBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PRIMEFIN.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
HAKKANIPUL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ADNTEL.csv
[]
SIBL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
NBL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
IBNSINA.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SPCL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
GP.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
APEXFOOT.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
NAVANACNG.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
NATLIFEINS.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
EXIMBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BEACONPHAR.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
LINDEBD.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ONEBANKLTD.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BATBC.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
GENEXIL.csv
[]
PIONEERINS.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
IDLC.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
FAREASTLIF.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BSRMLTD.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
DESCO.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ACIFORMULA.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
GREENDELT.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
HEIDELBCEM.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
EBL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
JAMUNABANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
IPDC.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
DHAKABANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SHAHJABANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
LANKABAFIN.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
KDSALTD.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
AFTABAUTO.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
GPHISPAT.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SEAPEARL.csv
[]
FORTUNE.csv
[]
SKTRIMS.csv
[]
STANDBANKL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BEXIMCO.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ORIONPHARM.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ALARABANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
DOREENPWR.csv
[datetime.date(2016, 9, 24), datetime.date(2016, 7, 16)]
BANKASIA.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
JAMUNAOIL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
DELTALIFE.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SAIFPOWER.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
EHL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
NHFIL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BSRMSTEEL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
MALEKSPIN.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SOUTHEASTB.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
RELIANCINS.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ORIONINFU.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
FIRSTSBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PADMAOIL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
CONFIDCEM.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PUBALIBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BDWELDING.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
APOLOISPAT.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SAPORTL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
NTC.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
UCB.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
GOLDENSON.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
MARICO.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ISLAMIBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PROVATIINS.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ACMELAB.csv
[datetime.date(2016, 9, 24), datetime.date(2016, 7, 16)]
AMANFEED.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ABBANK.csv
[datetime.date(2020, 1, 8), datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
MJLBD.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
POPULARLIF.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
CITYBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
PREMIERBAN.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
RNSPIN.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
DUTCHBANGL.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ENVOYTEX.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ATLASBANG.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
MLDYEING.csv
[]
PENINSULA.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SINGERBD.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ECABLES.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
KOHINOOR.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
BPML.csv
[]
POWERGRID.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
ICB.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
INTRACO.csv
[]
MPETROLEUM.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
TRUSTBANK.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
OLYMPIC.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
UTTARAFIN.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
MTB.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]
SQURPHARMA.csv
[datetime.date(2016, 9, 24), datetime.date(2015, 12, 31), datetime.date(2016, 7, 16)]

                  open        high         low       close    volume
date
2012-01-01   42.054283   42.054283   41.225232   41.907193   24255.0
2012-01-02   41.472610   41.472610   41.218546   41.405751   25740.0
2012-01-03   41.325520   41.673187   41.318834   41.439180   37125.0
2012-01-04   41.385693   41.719988   41.385693   41.512725   73755.0
2012-01-05   41.619700   41.619700   41.318834   41.419123   31680.0
...                ...         ...         ...         ...       ...
2021-12-26  639.000000  639.000000  625.100000  627.200000  207369.0
2021-12-27  626.300000  633.700000  622.500000  623.800000  167286.0
2021-12-28  624.000000  640.000000  624.000000  637.200000   88461.0
2021-12-29  640.000000  647.000000  630.800000  634.500000  120326.0
2021-12-30  634.800000  639.800000  632.700000  635.600000   95882.0

[2365 rows x 5 columns]

In [33]:
len(data.index)

2363

In [49]:
df = pd.read_csv("./before_process_data/data/BATBC.csv", index_col=0, parse_dates=True)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3273 entries, 2008-03-06 to 2021-12-30
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   open            3273 non-null   float64
 1   high            3273 non-null   float64
 2   low             3273 non-null   float64
 3   close           3273 non-null   float64
 4   volume          3273 non-null   int64
 5   dividend        3273 non-null   float64
 6   stock_dividend  3273 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 204.6 KB

In [51]:

# ex_date   amount  sid record_date declared_date pay_date payment sid
tmp = df[df["stock_dividend"] != 0.0]["stock_dividend"]
stock_div = pd.DataFrame(data=tmp.index.tolist(), columns=["ex_date"])
stock_div["record_date"] = pd.NaT
stock_div["declared_date"] = pd.NaT
stock_div["pay_date"] = pd.NaT
stock_div["ratio"] = tmp.tolist()
stock_div["sid"] = pd.Series(1, index=tmp.index)
stock_div["payment_sid"] = pd.Series(1, index=tmp.index)

In [66]:
stock_div.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ex_date        3 non-null      datetime64[ns]
 1   record_date    0 non-null      datetime64[ns]
 2   declared_date  0 non-null      datetime64[ns]
 3   pay_date       0 non-null      datetime64[ns]
 4   ratio          3 non-null      float64
 5   sid            0 non-null      float64
 6   payment_sid    0 non-null      float64
dtypes: datetime64[ns](4), float64(3)
memory usage: 296.0 bytes

In [55]:
divs_splits_stdivs = {
    "divs": pd.DataFrame(
        columns=[
            "sid",
            "amount",
            "ex_date",
            "record_date",
            "declared_date",
            "pay_date",
        ]
    ),
    "splits": pd.DataFrame(columns=["sid", "ratio", "effective_date"]),
    "stdivs": pd.DataFrame(
        columns=[
            "sid",
            "ex_date",
            "declared_date",
            "pay_date",
            "record_date",
            "payment_sid",
            "ratio",
        ]
    ),
}

In [75]:
stock_div = pd.DataFrame(data=tmp.index.tolist(), columns=["ex_date"])

In [76]:
stock_div

     ex_date
0 2012-03-15
1 2019-04-07
2 2021-03-04

In [ ]:
ind = pd.Index(
range(stdivs.shape[0], stdivs.shape[0] + stock_div.shape[0])
)
stock_div.set_index(ind, inplace=True)

divs_splits_stdivs["stdivs"] = stdivs.append(stock_div).astype(dtype={
    'sid': 
})

In [72]:
ind = pd.to_datetime(pd.Index(
range(stdivs.shape[0], stdivs.shape[0] + stock_div.shape[0])
))

In [73]:
ind

DatetimeIndex(['1970-01-01 00:00:00.000000003',
               '1970-01-01 00:00:00.000000004',
               '1970-01-01 00:00:00.000000005'],
              dtype='datetime64[ns]', freq=None)

In [77]:
divs_splits_stdivs['divs']

Empty DataFrame
Columns: [sid, amount, ex_date, record_date, declared_date, pay_date]
Index: []

In [60]:
stock_div_payout["record_date"] = (
                stock_div_payout["record_date"]
                .values.astype("datetime64[s]")
                .astype('int64'))

ValueError: cannot convert float NaN to integer

In [62]:
stock_div_payout.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sid            0 non-null      object
 1   ex_date        3 non-null      object
 2   declared_date  0 non-null      object
 3   pay_date       0 non-null      object
 4   record_date    0 non-null      object
 5   payment_sid    0 non-null      object
 6   ratio          3 non-null      object
dtypes: object(7)
memory usage: 192.0+ bytes

In [63]:
dfss = pd.Series(pd.NaT, index=range(10))

In [65]:
dfss.info()

<class 'pandas.core.series.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: None
Non-Null Count  Dtype
--------------  -----
0 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 208.0 bytes